version: 2

jobs:
  build:
    working_directory: ~/micarrito
    docker:
      - image: circleci/node:9

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          key: install-dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run:
          name: Test
          command: npm test
